Repository MOONSHOT-Team/MOONSHOT-CLIENT, pull requests merged in 2024-05, with the labels that each got.

#276 [SP2/refacor] AddOkr : addOkr objTitleCateg 관련 개선 사항 반영
  src/AddOkr/components/stepLayout/ObjTitleCateg.tsx
Labels: 🔨 Refactor, ➕ AddOkr, 2️⃣ SP2

#277 [SP2/Feat] 랜딩페이지 유저 플로우 변경
  src/Router.tsx
Labels: ✨ Feature, 2️⃣ SP2

#285 [SP2/chore] 랜딩페이지 워딩 수정
  src/Onboarding/assets/frame/imgFrame4SideSheetLeft.png
  src/Onboarding/assets/frame/imgFrame4SideSheetRight.png
  src/Onboarding/assets/frame/imgFrame5List4.png
  src/Onboarding/assets/frame/webpFrame4SideSheetLeft.webp
  src/Onboarding/assets/frame/webpFrame4SideSheetRight.webp
  src/Onboarding/components/frame/Frame1.tsx
  src/Onboarding/components/frame/Frame2.tsx
  src/Onboarding/components/frame/Frame3.tsx
  src/Onboarding/components/frame/Frame4.tsx
  src/Onboarding/components/frame/Frame5.tsx
  src/Onboarding/components/frame/TextField.tsx
  src/Onboarding/constants/CONTENTS.ts
Labels: 2️⃣ SP2

#283 [SP2/feat] 클릭된 KR활성화 디자인
  src/MainDashBoard/components/mainDashBoardOkrTree/MainDashKrNodes.tsx
  src/MainDashBoard/components/mainDashBoardOkrTree/MainDashboardOKRTree.tsx
  src/MainDashBoard/index.tsx
Labels: ✨ Feature, 🪧 MainDashboard, 2️⃣ SP2

#287 [SP2/Feat] 랜딩페이지 우상단 베타서비스 링크 수정
  src/Onboarding/components/frame/Frame1.tsx
  src/Onboarding/components/layout/OnboardingHeader.tsx
  src/Onboarding/constants/APPLY_LINK.ts
Labels: 2️⃣ SP2

#290 Refac/#281/refac side sheet
  src/MainDashBoard/components/mainDashBoardDrawer/GoalItem.tsx
  src/MainDashBoard/components/mainDashBoardDrawer/MainDashBoardDrawer.tsx
  src/MainDashBoard/components/sideSheet/KRPeriodSelect.tsx
  src/MainDashBoard/index.tsx
Labels: 2️⃣ SP2

#297 fix: error페이지에 헤더 없애기
  src/common/components/Error/index.tsx
Labels: 2️⃣ SP2

#295 fix: url 경로 수정
  src/Onboarding/components/layout/OnboardingFooter.tsx
Labels: 2️⃣ SP2
