Repository MOONSHOT-Team/MOONSHOT-CLIENT, pull requests merged in 2024-04, with the labels that each got.

#253 [SP1/refactor] editOKR #140 코드리뷰 반영
  src/AddOkr/components/addKr/KeyResultPeriodInput.tsx
  src/MainDashBoard/components/editModeModal/AddKrModal.tsx
  src/MainDashBoard/components/editOkrTree/EditKrNodes.tsx
  src/MainDashBoard/components/editOkrTree/EditOKRTree.tsx
  src/MainDashBoard/components/editOkrTree/EditObjectNode.tsx
  src/MainDashBoard/components/editOkrTree/EditTaskNodes.tsx
  src/MainDashBoard/components/mainDashBoardOkrTree/EditBtn.tsx
  src/MainDashBoard/components/mainDashBoardOkrTree/MainDashObjectNode.tsx
  src/MainDashBoard/components/mainDashBoardOkrTree/MainDashboardOKRTree.tsx
  src/MainDashBoard/constants/OKRTREEVIEWS.ts
  src/MainDashBoard/styles/mainDashOKRTreeStyles.ts
  src/common/components/Modal/index.tsx
  src/common/components/input/DynamicInput.tsx
Labels: 🔨 Refactor, 1️⃣ SP1, 🖌️ editOKR

#260 [SP1/refactor] dynamic input 사용성 개선
  src/common/components/input/DynamicInput.tsx
Labels: 🔨 Refactor, 1️⃣ SP1

#265 [SP1/Chore] 약관 링크 넣기
  src/Onboarding/components/layout/OnboardingFooter.tsx
Labels: 1️⃣ SP1

#262 [SP1/refactor] 히스토리 리팩토링
  src/History/apis/fetcher.ts
  src/History/assets/icons/icCheck.svg
  src/History/assets/icons/icDropDown.svg
  src/History/assets/icons/icSmallDropDown.svg
  src/History/assets/icons/index.ts
  src/History/components/HistoryDrawer.tsx
  src/History/components/ThemeButton.tsx
  src/History/components/YearButton.tsx
  src/History/components/drawer/CategoryContainer.tsx
  src/History/components/drawer/HistoryDrawer.tsx
  src/History/components/dropDown/HistoryList.tsx
  src/History/components/dropDown/HistoryListDetails.tsx
  src/History/components/dropDown/KeyResultList.tsx
  src/History/components/dropDown/ListOrder.tsx
  src/History/components/dropDown/TaskList.tsx
  src/History/components/dropdown/Filters.tsx
  src/History/components/historyData/HistoryList.tsx
  src/History/components/historyData/HistoryProgressBar.tsx
  src/History/components/historyData/historyItemWrappers/HistoryKeyResult.tsx
  src/History/components/historyData/historyItemWrappers/HistoryObjective.tsx
  src/History/components/historyData/historyItemWrappers/HistoryTask.tsx
  src/History/constants/HISTORY_THEME.ts
  src/History/constants/LIST_ORDER.ts
  src/History/index.tsx
  src/History/type/historyData.ts
Labels: 🔨 Refactor, 1️⃣ SP1
